options:
  user:
    type: string
    description: 'The database user name.'
    default: 'admin'
  database:
    type: string
    description: 'The database name.'
    default: 'mssql'
  root_password:
    type: string
    description: 'The database root password.'
    default: 'MSSQL_SA_PASSWORD'
  image:
    type: string
    name: mssql
    description: 'The docker image to install.'
    default: mcr.microsoft.com/mssql/server:2017-latest
  ports:
      type: string
      description: |
        Ports to expose, space separated list in name:8000 format. Names are
        alphanumeric + hyphen. For example: "http:80 metrics:7127"
      default: tcp:1433
  container_secrets:
      type: string
      description: |
          YAML formatted map of secrets. Works just like container_config.
      default: "{'name': 'MSSQL_SA_PASSWORD',
                'type': Opaque,
                'data': {
                  username: 'SA_PASSWORD',
                  password: 'MyC0m9l&xP@ssw0rd',
                  },
                }"