options:
  database:
    type: string
    description: 'The database name.'
    default: 'mssql'
  image:
    type: string
    name: mssql
    description: 'The docker image to install.'
    default: mcr.microsoft.com/mssql/server:2017-latest
  ports:
      type: string
      description: |
        List of YAML formatted map of ports to expose. To add more than one,
        simply follow the format [{map1},{map2}]
      default: "[{'name': 'mssql',
                'containerPort': 1433,
                'protocol': 'TCP'}]"
  container_config:
    type: string
    default: "{'MSSQL_PID': 'developer',
              'ACCEPT_EULA': 'Y',
              }"
  container_secrets:
      type: string
      description: |
          YAML formatted map of secrets. Works just like container_config.
      default: ""
