options:
  database:
    type: string
    description: 'The database name.'
    default: 'mssql'
  image:
    type: string
    name: mssql
    description: The docker image to install.
    default: mcr.microsoft.com/mssql/server:2017-latest
  ports:
      type: string
      description: |
        List of YAML formatted map of ports to expose. To add more than one,
        simply follow the format [{map1},{map2}].
      default: "[{'name': 'mssql',
                'containerPort': 1433,
                'protocol': 'TCP'}]"
  container_config:
    type: string
    description: The MSSQL_PID refers to the type of license used by the user.
    default: "{'MSSQL_PID': 'developer',
              'ACCEPT_EULA': 'Y',
              }"
  container_secrets:
      type: string
      description: |
          YAML formatted map of secrets. Works just like container_config.
      default: ""
  sa_password:
      type: string
      description: |
        Complex password for the system administrator (SA) of the database.
        It requires 8 characters, uppercase, lowercase, alphanumerical
        and/or non-alphanumerical.
      default: 'MyC0m9l&xP@ssw0rd'